# Generated by Django 3.1.3 on 2020-11-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ahmed', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='books_list',
            name='author',
            field=models.ForeignKey(default='ahmed', on_delete=django.db.models.deletion.CASCADE, to='books.author_book'),
        ),
    ]
