# Generated by Django 3.1.3 on 2020-11-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201114_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_list',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
